

global COLOR_NAMES = Dictionary \
	#( 	#GREEN, 	green	) \
	#( 	#RED, 	red	) \
	#( 	#BLUE, 	blue	) \

	#( 	#ORANGE,	color 225	60	0	) \
	#( 	#MAGENTA,	color 225	0	255	) \
	#( 	#PINK, 	color 190	100	120	) \
	#( 	#CYAN, 	color 0	255	255	) \
	#( 	#darkGreen, 	color 0	135	75	) \
	#( 	#lightGreen, 	color 100	255	100	) \
	#( 	#WHITE, 	color 255	255	255	) \
	#( 	#BLACK, 	color 0	0	0	) \
	#( 	#YELLOW, 	color 255	255	0	) \
	#( 	#BROWN, 	color 139	69	19	) \
	#( 	#GRAY, 	color 128	128	128	) 